### ISSUE TITLE
Go Pandoc & Reveal.js

### ISSUE THREAD

**Issue by sungsit** [fontuni/boonjot#17]
For #6
- [x] [pandoc](http://pandoc.org/) only v1.15+ : markdown -> html (slides)
- [x] [reveal.js](https://github.com/hakimel/reveal.js/): slides -> pdf

**Comment by sungsit** [comment]
## To-do
- [x] Check print.css & also test dark bg color.  
- [x] Add sample pdf to repos or add instruction to print directly from browser.
- [x] Add css via pandoc options, no need to add customized theme.
- [x] Use reveal.js from upstream repo instead of the forked.
