### ISSUE TITLE
Latin feature checklist

### ISSUE THREAD

**Issue by sungsit** [fontuni/boonjot#4]
To-do:
- [x] `liga` fi fl, else?
- [x] `mark` for both pre-composed & combined glyphs
- [x] `locl` for Romainian, Moldovan
- [x] `frac` superior & inferior classes
- [x] `sups`, `subs`, `numr` & `dnom` superior & inferior classes
- [x] `tnum`, `pnum` superior & inferior classes
- [x] `kern` don't forget pre-composed

**Comment by sungsit** [comment]
Kerning is still weird on Firefox, maybe more related to CSS or Reveal.js than OT. This can be closed when #15 done.
